// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/protobufDemo/proto/Calculator.proto

package com.protobufDemo.protogen;

public final class Calculator {
  private Calculator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf service {@code CalculatorService}
   */
  public static abstract class CalculatorService
      implements com.google.protobuf.Service {
    protected CalculatorService() {}

    public interface Interface {
      /**
       * <code>rpc add(.RequestProto) returns (.ResponseProto);</code>
       */
      public abstract void add(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done);

      /**
       * <code>rpc minus(.RequestProto) returns (.ResponseProto);</code>
       */
      public abstract void minus(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CalculatorService() {
        @java.lang.Override
        public  void add(
            com.google.protobuf.RpcController controller,
            com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
            com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done) {
          impl.add(controller, request, done);
        }

        @java.lang.Override
        public  void minus(
            com.google.protobuf.RpcController controller,
            com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
            com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done) {
          impl.minus(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.add(controller, (com.protobufDemo.protogen.CalculatorMsg.RequestProto)request);
            case 1:
              return impl.minus(controller, (com.protobufDemo.protogen.CalculatorMsg.RequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.protobufDemo.protogen.CalculatorMsg.RequestProto.getDefaultInstance();
            case 1:
              return com.protobufDemo.protogen.CalculatorMsg.RequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance();
            case 1:
              return com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc add(.RequestProto) returns (.ResponseProto);</code>
     */
    public abstract void add(
        com.google.protobuf.RpcController controller,
        com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
        com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done);

    /**
     * <code>rpc minus(.RequestProto) returns (.ResponseProto);</code>
     */
    public abstract void minus(
        com.google.protobuf.RpcController controller,
        com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
        com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.protobufDemo.protogen.Calculator.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.add(controller, (com.protobufDemo.protogen.CalculatorMsg.RequestProto)request,
            com.google.protobuf.RpcUtil.<com.protobufDemo.protogen.CalculatorMsg.ResponseProto>specializeCallback(
              done));
          return;
        case 1:
          this.minus(controller, (com.protobufDemo.protogen.CalculatorMsg.RequestProto)request,
            com.google.protobuf.RpcUtil.<com.protobufDemo.protogen.CalculatorMsg.ResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.protobufDemo.protogen.CalculatorMsg.RequestProto.getDefaultInstance();
        case 1:
          return com.protobufDemo.protogen.CalculatorMsg.RequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance();
        case 1:
          return com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.protobufDemo.protogen.Calculator.CalculatorService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void add(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.protobufDemo.protogen.CalculatorMsg.ResponseProto.class,
            com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance()));
      }

      public  void minus(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.protobufDemo.protogen.CalculatorMsg.ResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.protobufDemo.protogen.CalculatorMsg.ResponseProto.class,
            com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.protobufDemo.protogen.CalculatorMsg.ResponseProto add(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException;

      public com.protobufDemo.protogen.CalculatorMsg.ResponseProto minus(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.protobufDemo.protogen.CalculatorMsg.ResponseProto add(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException {
        return (com.protobufDemo.protogen.CalculatorMsg.ResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance());
      }


      public com.protobufDemo.protogen.CalculatorMsg.ResponseProto minus(
          com.google.protobuf.RpcController controller,
          com.protobufDemo.protogen.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException {
        return (com.protobufDemo.protogen.CalculatorMsg.ResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.protobufDemo.protogen.CalculatorMsg.ResponseProto.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:CalculatorService)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1main/java/com/protobufDemo/proto/Calcu" +
      "lator.proto\0324main/java/com/protobufDemo/" +
      "proto/CalculatorMsg.proto2a\n\021CalculatorS" +
      "ervice\022$\n\003add\022\r.RequestProto\032\016.ResponseP" +
      "roto\022&\n\005minus\022\r.RequestProto\032\016.ResponseP" +
      "rotoB-\n\031com.protobufDemo.protogenB\nCalcu" +
      "lator\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protobufDemo.protogen.CalculatorMsg.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
